Add new image for user_saml_shibboleth-php8.0
nextcloud/docker-ci pull request #359
Opened 2022-03-01 20:49 UTC by blizzz

2022-03-02 11:27 UTC, CarlSchwan approved these changes

2022-03-21 11:54 UTC, artonge commented on user_saml_shibboleth-php7.3/start.sh
>  run-jetty.sh
```suggestion
run-jetty.sh &
```

2022-03-21 11:54 UTC, artonge commented on user_saml_shibboleth-php7.3/Dockerfile
> +	&& kill -INT "$(ps -C ns-slapd -o pid h)" \
So, it looks like slapd is creating a file here with the process number: `/var/lock/dirsrv/slapd-dir/server`

Killing it with `INT` do not allow it to delete this file.
Killing it with `TERM` does.

```suggestion
 	&& kill -TERM "$(ps -C ns-slapd -o pid h)" \
```

Only tested it once, and the lock file is not here anymore so CI should be happier, crossing finger hard that it is 'simply' it :)

2022-03-28 10:49 UTC, artonge requested changes

2022-03-28 10:49 UTC, artonge commented on user_saml_shibboleth-php8.0/Dockerfile
> +    && kill -INT "$(ps -C ns-slapd -o pid h)" \
```suggestion
    && kill -TERM "$(ps -C ns-slapd -o pid h)" \
```

2022-03-28 11:52 UTC, artonge approved these changes

2022-04-07 16:36 UTC, merged

2022-04-08 18:21 UTC, blizzz commented
@artonge I think that was it. So far i have not seen a single failing test. Thank you so much!!