Add KArchive to client Dockerfiles
nextcloud/docker-ci pull request #386
Opened 2022-07-21 14:44 UTC by claucambra

This should fix failures with this PR on the desktop client side: https://github.com/nextcloud/desktop/pull/4768

2022-07-21 16:01 UTC, mgallien commented on client/Dockerfile
> +    git clone https://invent.kde.org/frameworks/karchive.git -b v5.96.0 && \
add `--depth 1` to make a swallow clone

2022-07-21 16:02 UTC, mgallien commented on client-appimage/Dockerfile
> +    git clone https://invent.kde.org/frameworks/extra-cmake-modules.git -b v5.96.0 && \
same comment

2022-07-21 16:02 UTC, mgallien commented on client-appimage/Dockerfile
> +    git clone https://invent.kde.org/frameworks/karchive.git -b v5.96.0 && \
same comment

2022-07-21 16:36 UTC, claucambra commented on client/Dockerfile
> +    git clone https://invent.kde.org/frameworks/karchive.git -b v5.96.0 && \
Okay, added `--depth 1`

2022-07-22 07:44 UTC, mgallien approved these changes

2022-07-22 07:46 UTC, mgallien requested changes
build of ecm framework is failing (speaks about missing sphinx module for qt docs and I cannot remember if that one is really mandatory or we could just disable it)

2022-07-22 14:12 UTC, claucambra commented
> build of ecm framework is failing (speaks about missing sphinx module for qt docs and I cannot remember if that one is really mandatory or we could just disable it)

Fixed the build :)

2022-07-28 11:24 UTC, mgallien approved these changes

2022-07-28 11:31 UTC, merged